### ISSUE TITLE
執行 plugin install 時發生 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Sevenflanks** [softleader/slctl#4]
沒有加上hook時沒有這個問題，加上hook想在安裝玩plugin後進行提醒時發生問題

metadata.yaml:
```
name: make
version: 0.1.0
usage: to Makefile without The Make but neet docker
description: Makefile with docker
exec:
  command: cmd /c docker run -it --rm -v ${pwd}:/data -v $(M2_HOME):/root/.m2/repository" softleader/fatca-make 
  platform:
  - os: darwin
    command: cmd /c docker run -it --rm -v ${pwd}:/data -v $(M2_HOME):/root/.m2" softleader/fatca-make 
  - os: windows
    command: cmd /c docker run -it --rm -v ${pwd}:/data -v %M2_HOME%:/root/.m2" softleader/fatca-make
hook:
  command: echo "please check this machine have M2_HOME"
ignoreglobalflags: false
```
run:
```
slctl plugin install .\slctl-make.zip -v

downloading the archive: .\slctl-make.zip
successfully downloaded and saved it to: C:\develop\bin\home\cache\archives\slctl-make.zip
extracting archive to C:\develop\bin\home\cache\plugins\slctl-make.zip
symlinking C:\develop\bin\home\cache\plugins\slctl-make.zip to C:\develop\bin\home\plugins\make
running hook: echo "please check this machine have M2_HOME"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x7b7ae5]

goroutine 1 [running]:
github.com/softleader/slctl/pkg/plugin.(*ErrNoCommandFound).Error(0x0, 0xc00011e940, 0x2)
        /Users/matt/go/src/github.com/softleader/slctl/pkg/plugin/command.go:13 +0x5
github.com/softleader/slctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000132000, 0xc000132500, 0xc000132a00, 0xc000176000)
        /Users/matt/go/src/github.com/softleader/slctl/vendor/github.com/spf13/cobra/command.go:864 +0x45f
github.com/softleader/slctl/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000132000, 0x4, 0x7)
        /Users/matt/go/src/github.com/softleader/slctl/vendor/github.com/spf13/cobra/command.go:800 +0x32
main.main()
        /Users/matt/go/src/github.com/softleader/slctl/cmd/slctl.go:34 +0x80
```
